### ISSUE TITLE
changing from scene to random colour not wworking

### ISSUE THREAD

**Issue by scholzmichael** [ToracX/DreamScreenCommander#4]
It seems there is a problem so change from any scene like Holiday, fireplace etc. to random colour.
If I understand correctly this should be set by "-a 0" followed by the coulour, followed by the brightness.
Whenever one of the other scenes (1-8) is active or was the last active before turning off and I want to activate random colour it does not seem to work. Switching to video works perfectly fine. 
My setup is a pi3b where I use a node red flow to control the dreamscreen.
It all seems to work except the "-a 0" and even that works with different colours as long as not any other scene was active before.
Any idea what the problem could be?
The only solution to get rid of the problem is by using the app to go back to random colour. 
Any help is appreciated.

**Comment by ToracX** [comment]
I think I just resolved this issue, could you please provide feedback if its working or not?

**Comment by scholzmichael** [comment]
You did, just implemented the beta and did a dirty quick test, it works perfectly fine. Thanks a lot for the extremely fast help!
Great job.
